name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push Docker Image for Patient Service
        run: |
          docker build -t ${{ secrets.ECR_REPO_URI_PATIENT }} ./microservices/patient
          docker push ${{ secrets.ECR_REPO_URI_PATIENT }}
      - name: Build and Push Docker Image for Appointment Service
        run: |
          docker build -t ${{ secrets.ECR_REPO_URI_APPOINTMENT }} ./microservices/appointment
          docker push ${{ secrets.ECR_REPO_URI_APPOINTMENT }}