name: Creating aws infra

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  provision:
    name: Terraform Infra via EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.11.4'

      - name: Terraform format
        run: cd terraform1 && terraform fmt

      - name: Terraform init
        run: cd terraform1 && terraform init

      - name: Terraform validate
        run: cd terraform1 && terraform validate

      - name: Terraform plan
        run: cd terraform1 && terraform plan

      - name: Terraform Apply
        run: cd terraform1 && terraform apply -auto-approve

      # - name: Terraform destroy
      #   run: cd terraform1 && terraform destroy -auto-approve